FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

RUN yarn run build

FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 81

CMD ["nginx", "-g", "daemon off;"]



